# Generated by Django 4.1.7 on 2023-02-16 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='notes',
        ),
        migrations.AddField(
            model_name='notes',
            name='note',
            field=models.FileField(blank=True, null=True, upload_to='./notes/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='nb_notes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
