# Generated by Django 4.1.7 on 2023-02-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_notes_notes_notes_note_subject_nb_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='name',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
