# Generated by Django 4.1.7 on 2023-02-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_notes_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='note',
            new_name='file',
        ),
    ]
