# Generated by Django 4.1.7 on 2023-02-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_rename_note_notes_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='notes',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
